#!/usr/bin/env python3
"""Generate PROMPTS.md: the single record of the conversation that built this
project.

It records, read from the local opencode session database:
  * every prompt Johannes typed, with the AI's answer to it;
  * every planning question the AI asked, with Johannes's answer.

The AI's internal reasoning and all tool activity (edits, commands, searches)
are left out. Nothing here is typed by hand.
"""

import json
import os
import re
import sqlite3
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO_SLUG = ROOT.name
DB = Path(os.environ.get("OPENCODE_DB", Path.home() / ".local/share/opencode/opencode.db"))


def blockquote(text):
    lines = (text or "").strip().splitlines()
    return "\n".join("> " + line if line.strip() else ">" for line in lines)


def when(ms):
    return datetime.fromtimestamp((ms or 0) / 1000).strftime("%Y-%m-%d %H:%M")


def parse_question(raw, ms):
    try:
        data = json.loads(raw)
    except (ValueError, TypeError):
        return None
    state = data.get("state", {}) or {}
    questions = (state.get("input", {}) or {}).get("questions", []) or []
    answers = (state.get("metadata", {}) or {}).get("answers", []) or []
    items = []
    for i, q in enumerate(questions):
        answer = answers[i] if i < len(answers) else []
        if isinstance(answer, list):
            answer = "; ".join(str(a) for a in answer) if answer else "(no answer recorded)"
        items.append((q.get("question", ""), str(answer)))
    if not items:
        return None
    return {"time": ms, "items": items}


def main():
    if not DB.exists():
        print("opencode database not found at %s; nothing to do." % DB)
        return
    con = sqlite3.connect("file:%s?mode=ro" % DB, uri=True)
    con.row_factory = sqlite3.Row
    session_ids = [
        r["id"]
        for r in con.execute(
            """
            SELECT id FROM session
            WHERE directory = :repo
               OR id IN (SELECT DISTINCT session_id FROM part WHERE data LIKE :pat)
            ORDER BY time_created
            """,
            {"repo": str(ROOT), "pat": "%" + REPO_SLUG + "%"},
        )
    ]
    if not session_ids:
        print("No sessions found for this project yet.")
        return

    placeholders = ",".join("?" for _ in session_ids)
    rows = con.execute(
        """
        SELECT p.time_created AS t, p.id AS pid,
               json_extract(m.data, '$.role') AS role,
               json_extract(p.data, '$.type') AS type,
               json_extract(p.data, '$.text') AS text,
               json_extract(p.data, '$.tool') AS tool,
               p.data AS raw
        FROM part p JOIN message m ON p.message_id = m.id
        WHERE p.session_id IN (%s)
        ORDER BY p.time_created, p.id
        """ % placeholders,
        session_ids,
    ).fetchall()

    prompts = []
    questions = []
    current = None
    for r in rows:
        if r["role"] == "user" and r["type"] == "text":
            if current:
                prompts.append(current)
            current = {"prompt": r["text"] or "", "time": r["t"], "parts": []}
        elif current is not None and r["role"] == "assistant":
            if r["type"] == "tool" and r["tool"] == "question":
                event = parse_question(r["raw"], r["t"])
                if event:
                    questions.append(event)
            current["parts"].append((r["type"], r["text"] or ""))
    if current:
        prompts.append(current)

    for ex in prompts:
        parts = ex["parts"]
        last_tool = max((j for j, (t, _) in enumerate(parts) if t == "tool"), default=-1)
        answer = "\n\n".join(
            txt for t, txt in parts[last_tool + 1:] if t == "text" and txt.strip()
        )
        if not answer.strip():
            tail = [txt for t, txt in parts if t == "text" and txt.strip()]
            answer = tail[-1] if tail else "_(no written answer recorded)_"
        ex["answer"] = answer

    out = []
    out.append("# Prompt log\n")
    out.append(
        "This file is generated by `prompts.py` from the local opencode session\n"
        "database. It is the single record of the conversation that built this\n"
        "project:\n\n"
        "- every prompt sent to the AI, in order, with the AI's answer to it;\n"
        "- every planning question the AI asked, with Johannes's answer.\n\n"
        "The AI's internal reasoning and all tool activity are left out. The numbers\n"
        "match the tags in `essay.md`: AI-written text tagged `[[AI:N]]` came from\n"
        "Prompt N below. Do not edit this file by hand; regenerate it with\n"
        "`prompts.py`.\n"
    )
    out.append("Last updated: %s\n" % datetime.now().strftime("%Y-%m-%d %H:%M"))

    out.append("## Planning questions and answers\n")
    out.append(
        "The AI asked these while working on the project. They are part of the\n"
        "record for the same reason as the prompts: nothing should have to be\n"
        "guessed.\n"
    )
    for event in questions:
        out.append("**%s**\n" % when(event["time"]))
        for question, answer in event["items"]:
            out.append('AI question — "%s"' % question)
            out.append("Answer: %s\n" % answer)

    out.append("---\n")
    out.append("## Prompts\n")
    for i, ex in enumerate(prompts, 1):
        out.append("## Prompt %d\n" % i)
        out.append("*%s*\n" % when(ex["time"]))
        out.append("**Prompt sent:**\n")
        out.append(blockquote(ex["prompt"]) + "\n")
        out.append("**AI reply:**\n")
        out.append(blockquote(ex["answer"]) + "\n")

    (ROOT / "PROMPTS.md").write_text("\n".join(out), encoding="utf-8")
    print("Wrote PROMPTS.md: %d prompt(s), %d question round(s)." % (len(prompts), len(questions)))


if __name__ == "__main__":
    main()
